version: '3'
name: caddy
services:
  caddy:
    container_name: caddy
    image: ghcr.io/williamjacksn/caddy-route53
    privileged: true
    restart: unless-stopped
    ports:
      # Map each IP to different ports so caddy can expose different services to each
      # This allows me to use public dns names, not need to type any port numbers and
      # only expose some of the services to the internet.
      - "[2401:d002:ca03:3503:d739:e80d:6f00:4210]:443:4000"
      - "[2401:d002:ca03:3503:d739:e80d:6f00:5000]:443:5000"
    volumes:
      - /mnt/container_data/caddy-config:/config
      - /mnt/container_data/caddy-data:/data
      - /mnt/container_data/caddy-Caddyfile:/etc/caddy/Caddyfile
