version: 0.15-1
mqtt:
  enabled: false

cameras:
  footpath:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/footpath
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.103:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      enabled: false
  frontyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.101:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      enabled: false
  upstairs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/upstairs
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.102:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      enabled: false
  downstairs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/downstairs
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.100:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      enabled: false

go2rtc:
  streams:
    footpath:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.103:554/Streaming/Channels/101
    frontyard:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.101:554/Streaming/Channels/101
    upstairs:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.102:554/Streaming/Channels/101
    downstairs:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.100:554/Streaming/Channels/101

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion