version: 0.15-1
mqtt:
  enabled: false

cameras:
  downstairs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.100:554/Streaming/Channels/101
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 2944
      height: 1656

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
