version: 0.15-1
mqtt:
  enabled: false

cameras:
  downstairs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/downstairs
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.100:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      enabled: false

go2rtc:
  streams:
    downstairs:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.254.100:554/Streaming/Channels/101

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion